// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_first_shield_powerup_pickup = "CgkIm-Xn1MEZEAIQDg"; // <GPGSID>
        public const string achievement_score_30_points = "CgkIm-Xn1MEZEAIQBQ"; // <GPGSID>
        public const string achievement_score_20_points = "CgkIm-Xn1MEZEAIQBA"; // <GPGSID>
        public const string achievement_score_90_points = "CgkIm-Xn1MEZEAIQCw"; // <GPGSID>
        public const string achievement_score_40_points = "CgkIm-Xn1MEZEAIQBg"; // <GPGSID>
        public const string achievement_score_5_points = "CgkIm-Xn1MEZEAIQAg"; // <GPGSID>
        public const string achievement_score_100_points = "CgkIm-Xn1MEZEAIQDA"; // <GPGSID>
        public const string achievement_first_upgrade = "CgkIm-Xn1MEZEAIQDQ"; // <GPGSID>
        public const string leaderboard_score_leaderboard = "CgkIm-Xn1MEZEAIQAQ"; // <GPGSID>
        public const string achievement_score_50_points = "CgkIm-Xn1MEZEAIQBw"; // <GPGSID>
        public const string achievement_score_80_points = "CgkIm-Xn1MEZEAIQCg"; // <GPGSID>
        public const string achievement_first_spawn_greens_powerup = "CgkIm-Xn1MEZEAIQDw"; // <GPGSID>
        public const string achievement_score_10_points = "CgkIm-Xn1MEZEAIQAw"; // <GPGSID>
        public const string achievement_score_70_points = "CgkIm-Xn1MEZEAIQCQ"; // <GPGSID>
        public const string achievement_score_60_points = "CgkIm-Xn1MEZEAIQCA"; // <GPGSID>

}

